import sys


def createcrackingreport(output, hash, algorithm, password, starttime, endtime, crackingmethod):
    report = open(output, 'a')
    report.write("\n\n")
    report.write(" _ _ _ _ _       _ _ _ _ _                \n")
    report.write("|  _ _ _ _|     |  _ _ _ _|               \n")
    report.write("| |             | |                       \n")
    report.write("| |_ _ _ _      | |                       \n")
    report.write("|  _ _ _ _|     | |                       \n")
    report.write("| |             | |                       \n")
    report.write("| |             | |_ _ _ _                \n")
    report.write("|_| A S T       |_ _ _ _ _| R A C K E R   \n")
    report.write("Operation: Cracking")
    report.write("\nStart date: ")
    report.write(starttime)
    report.write("\nEnd date: ")
    report.write(endtime)
    report.write("\nHashing algorithm: ")
    report.write(algorithm)
    report.write("\nCracking method: ")
    report.write(crackingmethod)
    report.write("\nHash: ")
    report.write(hash)
    report.write("\nPassword: ")
    report.write(password)
    report.write("\nOutput file: ")
    report.write(output)
    sys.exit(0)


def hashcreatereport(tocreate, hash, algorithm, output):
    report = open(output, 'a')
    report.write("\n\n")
    report.write(" _ _ _ _ _       _ _ _ _ _                \n")
    report.write("|  _ _ _ _|     |  _ _ _ _|               \n")
    report.write("| |             | |                       \n")
    report.write("| |_ _ _ _      | |                       \n")
    report.write("|  _ _ _ _|     | |                       \n")
    report.write("| |             | |                       \n")
    report.write("| |             | |_ _ _ _                \n")
    report.write("|_| A S T       |_ _ _ _ _| R A C K E R   \n")
    report.write("Operation: Hashing")
    report.write("\nHashing algorithm: ")
    report.write(algorithm)
    report.write("\nText: ")
    report.write(tocreate)
    report.write("\nHash: ")
    report.write(hash)
    report.write("\nOutput file: ")
    report.write(output)
    sys.exit(0)
